- name: update packages
  apt: update_cache=yes

- name: install required packages
  apt: name={{ item }} state=installed
  with_items:
    - python-pip
    - git
    - python3
    - python3-pip

- name: pass git key to server
  copy: 
    src=~/Ansible/keys/git_key
    dest=/home/ubuntu/.ssh/git_key 
    owner=ubuntu 
    mode=0644 
    force=no
    
- name: clone repo
  git: 
    repo=git@github.com:MujiLeica/COMP90024-Assignment2.git
    dest=/home/ubuntu/COMP90024-Twitter-Project/
    clone=yes
    accept_hostkey=yes
    key_file=/home/ubuntu/.ssh/git_key
   