- hosts: dbserver, harvesterserver, supportserver
  sudo: yes
  roles:
    - common

- hosts: dbserver
  sudo: yes
  roles:
    - config-dbserver

- hosts: harvesterserver
  sudo: yes
  roles:
    - config-harvesterserver
     
- hosts: webserver
  sudo: yes
  roles:
    - config-webserver
